### ISSUE TITLE
Trying to install (python 3.4.3)

### ISSUE THREAD

**Issue by gavinjackson** [fatzebra/fatzebra-python#1]
Gday, just trying to install on python 3.4.3 via pip (not sure if this module has been upgraded to support python 3 yet).

I can confirm that this package installs fine on python 2.7.

Cheers,
Gav

(pyvenv-zenkai) gavinj@red5:~$ pip install fatzebra
Downloading/unpacking fatzebra
  Downloading fatzebra-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-cvhf_e4h/fatzebra/setup.py) egg_info for package fatzebra
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-cvhf_e4h/fatzebra/setup.py", line 11, in <module>
        from fatzebra import version
      File "/tmp/pip-build-cvhf_e4h/fatzebra/fatzebra/**init**.py", line 1, in <module>
        import gateway
      File "/tmp/pip-build-cvhf_e4h/fatzebra/fatzebra/gateway.py", line 4, in <module>
        from . import data
    SystemError: Parent module '' not loaded, cannot perform relative import
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-cvhf_e4h/fatzebra/setup.py", line 11, in <module>

```
from fatzebra import version
```

  File "/tmp/pip-build-cvhf_e4h/fatzebra/fatzebra/**init**.py", line 1, in <module>

```
import gateway
```

  File "/tmp/pip-build-cvhf_e4h/fatzebra/fatzebra/gateway.py", line 4, in <module>

```
from . import data
```

SystemError: Parent module '' not loaded, cannot perform relative import

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-cvhf_e4h/fatzebra
Storing debug log for failure in /home/gavinj/.pip/pip.log

**Comment by amasses** [comment]
Hi Gavin,

I have updated the relative imports which appears (on my end) to fix this issue. A new version has been pushed to Github and PyPI (0.0.5). Can you please re-test and let me know if you are still unable to install?

Thanks,
Matthew

**Comment by gavinjackson** [comment]
Thanks Matt,

Installs perfectly on python 3!

Many thanks for looking into the issue.

Cheers,
Gav

{e} gavin.jackson@gmail.com {mb} 0422 443 980
{skype} gavin6252 {twitter} @gavz {blog} www.gavinj.net
{g+} profiles.google.com/gavin.jackson
